### ISSUE TITLE
Freezes on windows, jhipster 6.5.1

### ISSUE THREAD

**Issue by johnpoole** [vivekmore/generator-jhipster-nav-element#32] opened 2019-12-06 05:18 UTC
##### **Overview of the issue**

It freezes on a blank project as the first command after its created

##### **Motivation / Use Case**
Freezes
##### **Reproduce the error**

create a jhipster project, monolith, angular, maven, no testing
##### **JHipster Version(s)**

6.5.1

##### **JHipster configuration**

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
superior@0.0.1-SNAPSHOT C:\Users\John\Documents\superior
`-- generator-jhipster@6.5.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.drift.superior"
    },
    "jhipsterVersion": "6.5.1",
    "applicationType": "monolith",
    "baseName": "superior",
    "packageName": "com.drift.superior",
    "packageFolder": "com/drift/superior",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "journal",
    "clientThemeVariant": "light",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": []
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.8.3.windows.1

node: v10.15.3

npm: 6.9.0

yeoman: 2.0.0

yarn: 1.7.0

##### **Browsers and Operating System**

Windows
-   [ ] I have provided sufficient information to the best of my ability.

**Comment by vivekmore** [comment] 2019-12-06 14:10
I couldn't reproduce the issue.
![image](https://user-images.githubusercontent.com/2099329/70328880-176c4d00-1808-11ea-9c0d-dfb1d37be69c.png)

What were the inputs you gave to the `yo jhipster-nav-element` prompts?

Also I'm guessing you're using `generator-jhipster-nav-element@2.2.0`

**Comment by johnpoole** [comment] 2019-12-06 16:08
I only get the first prompt, for which I choose the first option: simple
page.

Then it just freezes.

Is there a log file or something I can look at?

**Comment by vivekmore** [comment] 2019-12-06 16:48
> Is there a log file or something I can look at?

I'm afraid there isn't.

**Comment by vivekmore** [comment] 2019-12-06 17:31
Also I'm not sure it's `freezing` as much as it's `wait`ing for user input.
Did you input your answer to the prompted question? If yes what was it?

**Comment by johnpoole** [comment] 2019-12-06 17:40
The only question was the type. I hit enter once. The previous version
worked for me a few months ago.

**Comment by johnpoole** [comment] 2019-12-06 19:15
Could you send me the output of your Jhipster info? Maybe something else is
different.

In particular, which version of node are you using? I've got v10.15.3

**Comment by vivekmore** [comment] 2019-12-07 17:42
Can you check the version of the module you're running? also what is the version of jhipster you used to generate your project?
```
jhipster --version

npm ls -g generator-jhipster-nav-element --depth=0
```

**Comment by johnpoole** [comment] 2019-12-07 18:21
PS C:\Users\John\Documents\superior> jhipster --version
INFO! Using JHipster version installed locally in current project's
node_modules
6.5.1

PS C:\Users\John\Documents\superior> npm ls -g
generator-jhipster-nav-element --depth=0
C:\Users\John\AppData\Roaming\npm
`-- generator-jhipster-nav-element@2.2.0

**Comment by vivekmore** [comment] 2019-12-07 18:43
> Could you send me the output of your Jhipster info? Maybe something else is different. In particular, which version of node are you using? I've got v10.15.3

```
$>jhipster --version
INFO! Using JHipster version installed locally in current project's node_modules
6.5.1

$>npm ls -g generator-jhipster-nav-element --depth=0
C:\Users\vivzt\AppData\Roaming\npm
`-- generator-jhipster-nav-element@2.2.0  -> C:\dev\idea\vivek\jhipster\generator-jhipster-nav-element

$>jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**


superior@0.0.1-SNAPSHOT C:\dev\idea\vivek\jhipster\jhne-32
`-- generator-jhipster@6.5.1



##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.drift.superior"
    },
    "jhipsterVersion": "6.5.1",
    "applicationType": "monolith",
    "baseName": "superior",
    "packageName": "com.drift.superior",
    "packageFolder": "com/drift/superior",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "journal",
    "clientThemeVariant": "light",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": []
  }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

git version 2.24.0.windows.2

node: v10.16.3

npm: 6.13.2

yeoman: 3.1.0

Docker version 19.03.1, build 74b1e89e8a

docker-compose version 1.24.1, build 4667896b

INFO! Congratulations, JHipster execution is complete!

```

**Comment by vivekmore** [comment] 2019-12-08 23:24
Just noticed that you might be using powershell, (not that it should matter) but I was not able to run `yo jhipster-nav-element` but was able to run `npx yo jhipster-nav-element` with no issues.

Can you confirm if your issue is resolved by using command prompt just to rule out that the problem is related to Power Shell?

**Comment by johnpoole** [comment] 2019-12-08 23:34
I tried the command  prompt, and then the command prompt as admin. It
didn't make any difference.

I also tried updating to the newest version of node/npm and got some errors
about failing to install chocolaty( whatever that is)

I got the message that yo is outdated after verifying the npm cache, but
updating it hasn't worked. It seems like npm or yo might be the problem.

**Comment by johnpoole** [comment] 2019-12-12 04:41
Installing/reinstalling yo with yarn got rid of the problem

**Comment by vivekmore** [comment] 2019-12-12 12:28
wow - thanks for reporting.

**Closed as completed by vivekmore** 2019-12-12 12:28 UTC
